# Copyright Â© 2024 Atlantic Algorithms Ltd.,
# CoreChainDB and Atlantic Algorithms Ltd. software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Building corechaindb Docker
  docker_image:
    name: "{{ corechaindb_image_name }}"
    state: build
    tag: "{{corechaindb_image_tag }}"
    dockerfile: Dockerfile-alpine
    path: "{{ home_dir }}/corechaindb"
    nocache: yes
    buildargs:
      backend: localmongodb
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [corechaindb]

- name: Start corechaindb Docker
  docker_container:
    name: "{{ corechaindb_docker_name }}{{ item }}"
    image: "{{ corechaindb_image_name }}:{{ corechaindb_image_tag }}"
    hostname: "{{ corechaindb_docker_name }}{{ item }}"
    detach: true
    network_mode: bridge
    networks:
      - name: "{{ corechaindb_docker_net }}"
    env:
      corechaindb_DATABASE_BACKEND: "localmongodb"
      corechaindb_DATABASE_HOST: "{{ mongodb_docker_name }}{{ item }}"
      corechaindb_DATABASE_PORT: "27017"
      corechaindb_SERVER_BIND: "0.0.0.0:9984"
      corechaindb_WSSERVER_HOST: "0.0.0.0"
      corechaindb_TENDERMINT_HOST: "{{ tendermint_docker_name }}{{ item }}"
      corechaindb_TENDERMINT_PORT: "{{ corechaindb_tendermint_port | string }}"
    published_ports:
      - "{{ corechaindb_default_server_port }}"
      - "{{ corechaindb_default_ws_port }}"
      - "{{ tendermint_abci_port }}"
    restart_policy: always
    state: started
    command: corechaindb -l DEBUG start
  with_sequence: start=1 end="{{ stack_size|int }}" stride=1
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [corechaindb]

- import_tasks: debian.yml
  when: stack_type == "local" and (distribution_name == "debian" or distribution_name == "ubuntu")
  tags: [corechaindb]

- import_tasks: centos.yml
  when: stack_type|lower == "local" and (distribution_name == "centos" or distribution_name == "red hat enterprise linux")
  tags: [corechaindb]

- import_tasks: fedora.yml
  when: stack_type|lower == "local" and (distribution_name == "fedora")
  tags: [corechaindb]

- import_tasks: common.yml
  when: stack_type|lower == "local"
  tags: [corechaindb]